//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventoryManager.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE dbo.rawInventory
        ///SET qtyTotalAvailable = (qtySti + qtySglc + @value), qtySglc = (qtySglc + @value)
        ///WHERE partNumber = @partNum;.
        /// </summary>
        internal static string addSglcInventory {
            get {
                return ResourceManager.GetString("addSglcInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE dbo.rawInventory
        ///SET qtyTotalAvailable = (qtySti + qtySglc + @value), qtySTI = (qtySti + @value)
        ///WHERE partNumber = @partNum;.
        /// </summary>
        internal static string addStiInventory {
            get {
                return ResourceManager.GetString("addStiInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;@Server=den1.mssql4.gear.host;Database=stiinventory;User Id=stiinventory;Password=Freedom294238!@&quot;.
        /// </summary>
        internal static string dbconnection {
            get {
                return ResourceManager.GetString("dbconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE dbo.rawInventory
        ///SET qtyTotalAvailable = (qtySti + qtySglc - @value), qtySglc = (qtySglc - @value)
        ///WHERE partNumber = @partNum;.
        /// </summary>
        internal static string removeSglcinventory {
            get {
                return ResourceManager.GetString("removeSglcinventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE dbo.rawInventory
        ///SET qtyTotalAvailable = (qtySti + qtySglc - @value), qtySTI = (qtySti - @value)
        ///WHERE partNumber = @partNum;.
        /// </summary>
        internal static string removeStiInventory {
            get {
                return ResourceManager.GetString("removeStiInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE rawInventory
        ///SET qtySti = (qtySti + @in), qtySglc = (qtySglc - @out)
        ///WHERE partNumber = @partNum.
        /// </summary>
        internal static string transferSglctoSti {
            get {
                return ResourceManager.GetString("transferSglctoSti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE rawInventory
        ///SET qtySti = (qtySti - @out), qtySglc = (qtySglc + @in)
        ///WHERE partNumber = @partNum.
        /// </summary>
        internal static string transferStitoSglc {
            get {
                return ResourceManager.GetString("transferStitoSglc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM dbo.rawInventory;.
        /// </summary>
        internal static string viewRawInventoryQuery {
            get {
                return ResourceManager.GetString("viewRawInventoryQuery", resourceCulture);
            }
        }
    }
}
